#!/usr/bin/env bash

# A script to turn the logs generated by `docker compose -f docker-compose.yml up > logs.txt` into a csv file

FILENAME=${1}
OUTPUT=`basename -s '.txt' $FILENAME`.csv

grep 'MEASURE' $FILENAME | cut -d '|' -f 2 |
    sed -E "s/info|INFO|MEASURE=|\[|\]//g" | awk '{$1=$1};1' | sed -E "s/ /,/g" |
    awk -F ',' 'BEGIN{OFS=",";} {print $2, $3, $4, $1}' > $OUTPUT
