version: "3.9"
services:
  clock:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=clock
    hostname: clock

  manufacturer:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=manufacturer
    hostname: manufacturer

  consumer:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=consumer
    hostname: consumer

  producer:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=producer
    hostname: producer
