version: "3.9"
services:
  clock:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - NAME=clock
      - PLATFORM=clock_platform
    hostname: clock

  manufacturer:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - NAME=manufacturer
      - PLATFORM=manufacturer_platform
    hostname: manufacturer

  consumer:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - NAME=consumer
      - PLATFORM=consumer_platform
    hostname: consumer

  producer:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - NAME=producer
      - PLATFORM=producer_platform
    hostname: producer
