version: "3.9"
services:
  clock:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=clock
      - EXPERIMENT=experiment5
    hostname: clock

  manufacturer:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=manufacturer
      - EXPERIMENT=experiment5
    hostname: manufacturer

  consumer:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=consumer
      - EXPERIMENT=experiment5
    hostname: consumer

  producer_cpu_slow:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=producer
      - AGENT_NAME=producer_cpu_slow
      - SUB_TYPE=cpu_slow
      - EXPERIMENT=experiment5
    hostname: producer_cpu_slow

  producer_cpu_fast:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=producer
      - AGENT_NAME=producer_cpu_fast
      - SUB_TYPE=cpu_fast
      - EXPERIMENT=experiment5
    hostname: producer_cpu_fast

  producer_memory_small:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=producer
      - AGENT_NAME=producer_memory_small
      - SUB_TYPE=memory_small
      - EXPERIMENT=experiment5
    hostname: producer_memory_small

  producer_memory_large:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=producer
      - AGENT_NAME=producer_memory_large
      - SUB_TYPE=memory_large
      - EXPERIMENT=experiment5
    hostname: producer_memory_large

  producer_motherboard_one:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=producer
      - AGENT_NAME=producer_motherboard_one
      - SUB_TYPE=motherboard
      - EXPERIMENT=experiment5
    hostname: producer_motherboard_one

  producer_motherboard_two:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=producer
      - AGENT_NAME=producer_motherboard_two
      - SUB_TYPE=motherboard
      - EXPERIMENT=experiment5
    hostname: producer_motherboard_two

  producer_hard_drive_one:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=producer
      - AGENT_NAME=producer_hard_drive_one
      - SUB_TYPE=hard_drive
      - EXPERIMENT=experiment5
    hostname: producer_hard_drive_one

  producer_hard_drive_two:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=producer
      - AGENT_NAME=producer_hard_drive_two
      - SUB_TYPE=hard_drive
      - EXPERIMENT=experiment5
    hostname: producer_hard_drive_two
