version: "3.9"
services:
  clock:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=clock
      - EXPERIMENT=experiment1
    hostname: clock

  manufacturer:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=manufacturer
      - EXPERIMENT=experiment1
    hostname: manufacturer

  consumer:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=consumer
      - EXPERIMENT=experiment1
    hostname: consumer

  producer:
    build: .
    image: ghcr.io/glugg23/honours_project:jade
    environment:
      - AGENT_TYPE=producer
      - EXPERIMENT=experiment1
    hostname: producer
